name: Release Changelog Notification

on:
  pull_request:
    types: [ opened, edited, labeled ]
  pull_request_review:
    types: [ edited, dismissed ]

jobs:
  deployment_notification:
    runs-on: ubuntu-latest
    name: Release Changelog Notification
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: |
            Hi 2
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}